# This is a basic workflow to help you get started with Actions

name: Checking JQ version

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      rafay_project:
        type: choice
        description: 'Rafay Project name'
        required: true
        options:
          - development
          - qa
      rafay_cluster:
        type: string
        description: 'Rafay cluster name'
        required: true
        options:
          - development
          - qa
      alationfc_version:
        description: 'AlationFC helm chart image tag/version. by default latest image to be pulled'
        required: false
        default: 'latest'
      tenant_deployed_with_alationfc:
        type: text
        required: true
        description: 'single tenant id for which alationfc core is to be deployed'
      tenant1_namespace_dev_cluster_to_be_deployed:
        type: boolean
        required: true
        description: 'tenant1 namespace (c457ef59-4575-494b-8aa0-ba2e246b3a77) (of rafay dev cluster) to be deployed with alationfc ?'
      tenant2_namespace_dev_cluster_to_be_deployed:
        type: boolean
        required: true
        description: 'tenant2 namespace (c457ef59-4575-494b-8aa0-ba2e246b3a88) (of rafay dev cluster) to be deployed with alationfc ?'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      ALATION_FC_HELMCHART_LATEST_VERSION: ${{ github.event.inputs.alationfc_version }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: analying inputs and setting env variables accordingly
        run: |
          #if [ ${{ github.event.inputs.rafay_project }} == 'development' ]; then RAFAY_PROJECT_ID="gkj4g4k"; elif [ ${{ github.event.inputs.rafay_project }} == 'qa' ]; then RAFAY_PROJECT_ID='z24x37k'; else echo 'Invalid Rafay Project'; fi
          #if [ ${{ github.event.inputs.rafay_cluster }} == 'development' ]; then RAFAY_CLUSTER_ID="ky49w9k"; elif [ ${{ github.event.inputs.rafay_project }} == 'qa' ]; then RAFAY_CLUSTER_ID='24wdz7m'; else echo 'Invalid Rafay Cluster'; fi
          if [ ${{ github.event.inputs.tenant1_namespace_dev_cluster_to_be_deployed }} = true ]; then ALATION_FC_RAFAY_NAMESPACE_1='c457ef59-4575-494b-8aa0-ba2e246b3a77'; else ALATION_FC_RAFAY_NAMESPACE_1=''; fi
          if [ ${{ github.event.inputs.tenant2_namespace_dev_cluster_to_be_deployed }} = true ]; then ALATION_FC_RAFAY_NAMESPACE_2='c457ef59-4575-494b-8aa0-ba2e246b3a88'; else ALATION_FC_RAFAY_NAMESPACE_2=''; fi

          echo "${{ github.event.inputs.tenant1_namespace_dev_cluster_to_be_deployed }}"
          echo "tenant2 : ${{ github.event.inputs.tenant2_namespace_dev_cluster_to_be_deployed }}"
          #echo "RAFAY_PROJECT_ID=${RAFAY_PROJECT_ID}" >> $GITHUB_ENV
          #echo "RAFAY_CLUSTER_ID=${RAFAY_CLUSTER_ID}" >> $GITHUB_ENV
          echo "ALATION_FC_RAFAY_NAMESPACE_1=${ALATION_FC_RAFAY_NAMESPACE_1}" >> $GITHUB_ENV
          echo "ALATION_FC_RAFAY_NAMESPACE_2=${ALATION_FC_RAFAY_NAMESPACE_2}" >> $GITHUB_ENV
          
          echo "RAFAY_DEVELOPMENT_CLUSTER_NAME=development" >> $GITHUB_ENV
          echo "ALATION_DEVLOPMENT_RDS_MASTER_USER_PASSWORD=NjlkVmlwUkZKSkNENDhWazN2VWhEekZIQng0Ym0zZ0g=" >> $GITHUB_ENV
          echo "ALATION_DEVLOPMENT_RDS_MASTER_USERNAME=postgres" >> $GITHUB_ENV
          echo "ALATION_DEVLOPMENT_RDS_ENDPOINT=development.cegc5ylcvyxw.us-east-2.rds.amazonaws.com" >> $GITHUB_ENV
          echo "ALATION_DEVLOPMENT_RDS_PORT=5432" >> $GITHUB_ENV
          echo "RAFAY_DEVELOPMENT_CLUSTER_ID=ky49w9k" >> $GITHUB_ENV
          echo "RAFAY_DEVELOPMENT_PROJECT_ID=gkj4g4k" >> $GITHUB_ENV
          echo "RAFAY_DEVELOPMENT_PROJECT_NAME=development" >> $GITHUB_ENV
          echo "RAFAY_QA_CLUSTER_ID=24wdz7m" >> $GITHUB_ENV
          echo "RAFAY_QA_CLUSTER_NAME=qa" >> $GITHUB_ENV
          echo "RAFAY_QA_PROJECT_ID=z24x37k" >> $GITHUB_ENV
          echo "RAFAY_QA_PROJECT_NAME=qa" >> $GITHUB_ENV
          echo "ALATION_QA_RDS_MASTER_USER_PASSWORD=cUFBczJlNlJ5WTlnalR5cHJNN05uWFFNWVAyWHBveXc=" >> $GITHUB_ENV
          echo "ALATION_QA_RDS_MASTER_USERNAME=postgres" >> $GITHUB_ENV
          echo "ALATION_QA_RDS_ENDPOINT=qa.cegc5ylcvyxw.us-east-2.rds.amazonaws.com" >> $GITHUB_ENV
          echo "ALATION_QA_RDS_PORT=5432" >> $GITHUB_ENV
          
      - name: analying inputs and setting env variables accordingly
        run: |
          echo "input helm chart version is ${{ github.event.inputs.alationfc_version }}"
          echo "input rafay_project is ${{ github.event.inputs.rafay_project }}"
          echo "input rafay_cluster is ${{ github.event.inputs.rafay_cluster }}"
          echo "input tenant_deployed_with_alationfc is ${{ github.event.inputs.tenant_deployed_with_alationfc }}"

          #setting 'RAFAY_PROJECT_ID' variable
          if [ ${{ github.event.inputs.rafay_project }} == ${{ env.RAFAY_DEVELOPMENT_PROJECT_NAME }} ]; then RAFAY_PROJECT_ID=${{ env.RAFAY_DEVELOPMENT_PROJECT_ID }}; elif [ ${{ github.event.inputs.rafay_project }} == ${{ env.RAFAY_QA_PROJECT_NAME }} ]; then RAFAY_PROJECT_ID=${{ env.RAFAY_QA_PROJECT_ID }}; else echo 'Invalid Rafay Project'; fi
          echo "RAFAY_PROJECT_ID=${RAFAY_PROJECT_ID}" >> $GITHUB_ENV

          #setting 'RAFAY_CLUSTER_ID' variable
          if [ ${{ github.event.inputs.rafay_cluster }} == ${{ env.RAFAY_DEVELOPMENT_CLUSTER_NAME }} ]; then
            RAFAY_CLUSTER_ID=${{ env.RAFAY_DEVELOPMENT_CLUSTER_ID }};
            RAFAY_CLUSTER_NAME=${{ env.RAFAY_DEVELOPMENT_CLUSTER_NAME }}
            ALATION_RDS_DB_ENDPOINT=${{ env.ALATION_DEVLOPMENT_RDS_ENDPOINT }};
            ALATION_RDS_PORT=${{ env.ALATION_DEVLOPMENT_RDS_PORT }};
            ALATION_RDS_MASSTER_USERNAME=${{ env.ALATION_DEVLOPMENT_RDS_MASTER_USERNAME }};
            ALATION_RDS_MASTER_USER_PASSWORD=${{ env.ALATION_DEVLOPMENT_RDS_MASTER_USER_PASSWORD }};
          elif [ ${{ github.event.inputs.rafay_project }} == ${{ env.RAFAY_QA_CLUSTER_NAME }} ]; then
            RAFAY_CLUSTER_ID=${{ env.RAFAY_QA_CLUSTER_ID }};
            RAFAY_CLUSTER_NAME=${{ env.RAFAY_QA_CLUSTER_NAME }}
            ALATION_RDS_DB_ENDPOINT=${{ env.ALATION_QA_RDS_ENDPOINT }};
            ALATION_RDS_PORT=${{ env.ALATION_QA_RDS_PORT }};
            ALATION_RDS_MASTER_USER_PASSWORD=${{ env.ALATION_QA_RDS_MASTER_USERNAME }};
            ALATION_RDS_MASTER_USER_PASSWORD=${{ env.ALATION_QA_RDS_MASTER_USER_PASSWORD }};
          else echo 'Invalid Rafay Cluster';
          fi

          echo "RAFAY_CLUSTER_ID=${RAFAY_CLUSTER_ID}" >> $GITHUB_ENV
          echo "RAFAY_CLUSTER_NAME=${RAFAY_CLUSTER_NAME}" >> $GITHUB_ENV
          echo "ALATION_RDS_DB_ENDPOINT=${ALATION_RDS_DB_ENDPOINT}" >> $GITHUB_ENV
          echo "ALATION_RDS_PORT=${ALATION_RDS_PORT}" >> $GITHUB_ENV
          echo "ALATION_RDS_MASSTER_USERNAME=${ALATION_RDS_MASSTER_USERNAME}" >> $GITHUB_ENV
          echo "ALATION_RDS_MASTER_USER_PASSWORD=${ALATION_RDS_MASTER_USER_PASSWORD}" >> $GITHUB_ENV

          TENANT_ID=${{ github.event.inputs.tenant_deployed_with_alationfc }}
          echo "TENANT_ID=${TENANT_ID}" >> $GITHUB_ENV

          #if [ ${{ github.event.inputs.tenant1_namespace_dev_cluster_to_be_deployed }} = true ]; then ALATION_FC_RAFAY_NAMESPACE_1='c457ef59-4575-494b-8aa0-ba2e246b3a77'; else ALATION_FC_RAFAY_NAMESPACE_1=''; fi
          #if [ ${{ github.event.inputs.tenant2_namespace_dev_cluster_to_be_deployed }} = true ]; then ALATION_FC_RAFAY_NAMESPACE_2='c457ef59-4575-494b-8aa0-ba2e246b3a88'; else ALATION_FC_RAFAY_NAMESPACE_2=''; fi

          # For testing purpose
          RAFAY_PROJECT_ID="gkj4g4k"
          RAFAY_CLUSTER_ID="ky49w9k"
          TENANT_ID='c457ef59-4575-494b-8aa0-ba2e246b3a88'
          echo "RAFAY_PROJECT_ID=${RAFAY_PROJECT_ID}" >> $GITHUB_ENV
          echo "RAFAY_CLUSTER_ID=${RAFAY_CLUSTER_ID}" >> $GITHUB_ENV
          echo "ALATION_FC_RAFAY_NAMESPACE=${TENANT_ID}" >> $GITHUB_ENV
          
      - name: checking out env variables
        run: |
          echo "ALATION_FC_RAFAY_NAMESPACE_1 is ${{ env.ALATION_FC_RAFAY_NAMESPACE_1 }}"
          echo "ALATION_FC_RAFAY_NAMESPACE_2 is ${{ env.ALATION_FC_RAFAY_NAMESPACE_2 }}"
