# This is a basic workflow to help you get started with Actions

name: Checking JQ version

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - monalisa
        - cschleiden
      message:
        required: true
      use-emoji:
        type: boolean
        description: Include  emojis
      alationfc_version:
        description: 'AlationFC helm chart image tag/version. by default latest image to be pulled'
        required: false
        default: 'latest'
      tenant1_namespace_dev_cluster_to_be_deployed:
        type: boolean
        required: true
        description: 'tenant1 namespace (c457ef59-4575-494b-8aa0-ba2e246b3a77) (of rafay dev cluster) to be deployed with alationfc ?'
      tenant2_namespace_dev_cluster_to_be_deployed:
        type: boolean
        required: true
        description: 'tenant2 namespace (c457ef59-4575-494b-8aa0-ba2e246b3a88) (of rafay dev cluster) to be deployed with alationfc ?'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      ALATION_FC_HELMCHART_LATEST_VERSION: ${{ github.event.inputs.alationfc_version }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: analying inputs and setting env variables accordingly
        run: |
          #if [ ${{ github.event.inputs.rafay_project }} == 'development' ]; then RAFAY_PROJECT_ID="gkj4g4k"; elif [ ${{ github.event.inputs.rafay_project }} == 'qa' ]; then RAFAY_PROJECT_ID='z24x37k'; else echo 'Invalid Rafay Project'; fi
          #if [ ${{ github.event.inputs.rafay_cluster }} == 'development' ]; then RAFAY_CLUSTER_ID="ky49w9k"; elif [ ${{ github.event.inputs.rafay_project }} == 'qa' ]; then RAFAY_CLUSTER_ID='24wdz7m'; else echo 'Invalid Rafay Cluster'; fi
          if [ ${{ github.event.inputs.tenant1_namespace_dev_cluster_to_be_deployed }} = true ]; then ALATION_FC_RAFAY_NAMESPACE_1='c457ef59-4575-494b-8aa0-ba2e246b3a77'; else ALATION_FC_RAFAY_NAMESPACE_1=''; fi
          if [ ${{ github.event.inputs.tenant2_namespace_dev_cluster_to_be_deployed }} = true ]; then ALATION_FC_RAFAY_NAMESPACE_2='c457ef59-4575-494b-8aa0-ba2e246b3a88'; else ALATION_FC_RAFAY_NAMESPACE_2=''; fi

          #echo "RAFAY_PROJECT_ID=${RAFAY_PROJECT_ID}" >> $GITHUB_ENV
          #echo "RAFAY_CLUSTER_ID=${RAFAY_CLUSTER_ID}" >> $GITHUB_ENV
          echo "ALATION_FC_RAFAY_NAMESPACE_1=${ALATION_FC_RAFAY_NAMESPACE_1}" >> $GITHUB_ENV
          echo "ALATION_FC_RAFAY_NAMESPACE_2=${ALATION_FC_RAFAY_NAMESPACE_2}" >> $GITHUB_ENV
      - name: checking out env variables
        run: |
          echo "ALATION_FC_RAFAY_NAMESPACE_1 is ${{ env.ALATION_FC_RAFAY_NAMESPACE_1 }}"
          echo "ALATION_FC_RAFAY_NAMESPACE_2 is ${{ env.ALATION_FC_RAFAY_NAMESPACE_2 }}"
          
      - name: fetch latest tag/version of alationfc helm chart
        if: " ${{ github.event.inputs.alationfc_version }} == 'latest' "
        run: |
          echo "ALATION_FC_HELMCHART_LATEST_VERSION is ${ALATION_FC_HELMCHART_LATEST_VERSION}"
          
      - name: Check jq
        run: |
          jq --version
        shell: bash
      
      - name: Successful execution complted
      - run: |
          if [ ${{ github.event.inputs.tenant1_namespace_dev_cluster_to_be_deployed }} = true ]; then
            echo "alationfc/core publish to namespace ${{ env.ALATION_FC_RAFAY_NAMESPACE_1 }} of development Rafay cluster status is ${{ job.status }}"
          fi
          if [ ${{ github.event.inputs.tenant2_namespace_dev_cluster_to_be_deployed }} = true ]; then
            echo "alationfc/core publish to namespace ${{ env.ALATION_FC_RAFAY_NAMESPACE_2 }} of development Rafay cluster status is ${{ job.status }}"
          fi
