# This is a basic workflow to send workflow status to slack channel

name: workflow_send_status_to_slack_channel

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  notification:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Try to fail
        run: exit 1
      - name: slack - GitHub Actions Slack integration
        if: always()
        # You may pin to the exact commit or the version.
        # uses: act10ns/slack@da3191ebe2e67f49b46880b4633f5591a96d1d33
        uses: act10ns/slack@v1.5.0
        with:
          # Configuration file
          # Specify success, failure, cancelled or a custom status.
          status: ${{ job.status }}
          # Override default channel with different channel or username
          channel: #general
          # Override message format for step
          message: Test message from github actions
