# Github actions workflow to perform checks on pull request and JIRA ticket before merge.
# This workflow triggered by commenting 'check this please' on pull request
name: 'Check PR and JIRA'
on:
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

permissions:
  id-token: write
  contents: read
  pull-requests: read
  
jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-20.04
    steps:
      - run: |
          echo A comment on PR $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}
          
      # using action to fetch pull request (PR) details . This information will then be used in `pull_request_checks`custom GHA
      - name: Get PR base and target branch
        uses: xt0rted/pull-request-comment-branch@v1
        id: pr-comment-branch

      - name: Print PR details
        run: |
          echo Target branch is  ${{ steps.pr-comment-branch.outputs.base_ref }}

  issue_commented:
    # This job only runs for issue comments
    name: Issue comment
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on issue $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}
